---
title: "Figure 5 – AGTR1+ dopaminergic neuron vulnerability"
output: html_document
---

```{r setup}
library(ggplot2)
library(patchwork)
library(grid)
library(png)


load(here("data/processed/sn_atlas_annotated_subtype.RData"))
load(here("results/pseudotime/dan1_dan3.RData"))
dopamine_genes <- read.table("data/dopamine_genes.txt")
ras_genes <- read.table("data/ras_genes.txt")

sn_combined_dan <- subset(sn_combined_dan,subset=CellType=="DaN")
sn_combined_dan<-subset(sn_combined_dan,subset=Disease=="CTR")

prot_cod_len<-read.delim("data/gene_length",h=T)
data<-as.matrix(GetAssayData(sn_combined_dan, slot = "counts"))
prot_cod_m<-prot_cod_len[match(rownames(data),prot_cod_len[,1]),]
data <- sweep(data, 1, STATS = prot_cod_m$Gene_Length/1000, FUN = "/")
data[is.na(data)]<-0
data <- sweep(data, 2, STATS = colSums(data)/(10^6), FUN = "/")
SN_TPM_log_red<-log(data+1)

SN_TPM_log_red_dopamine<-SN_TPM_log_red[rownames(SN_TPM_log_red)%in%dopamine_genes[,1],]
SN_TPM_log_red_dopamine_t<-t(SN_TPM_log_red_dopamine)
SN_red_t_ord<-SN_TPM_log_red_dopamine_t
SN_red_t_ord<-as.data.frame(SN_red_t_ord)
SN_red_t_ord$cell_id<-sn_combined_dan$CellSubType
SN_TPM_log_red_dopamine_t_melt<-melt(SN_red_t_ord)


pA <- ggplot(SN_TPM_log_red_dopamine_t_melt,aes(x=variable,y=value,fill=cell_id))+
    geom_violin(trim=T, scale="width", adjust=0.8)+scale_fill_manual(values=c("lightgoldenrod1","goldenrod","tan1","darkorange3"))+
    theme_bw() +
      ggtitle("A")
pA

pB <- VlnPlot(sn_combined_dan,
              features=raas_genes,
              group.by="CellSubType") +
      ggtitle("B")
pB

imgC <- rasterGrob(readPNG("figures/raw_images/iPSC_DaN_AGTR1.png"))
grid.draw(imgC)

meta_toplot<-data.frame(ps=sce_dans$slingPseudotime_1,cellt=sce_dans$CellSubType)

pD <- ggplot(meta_toplot, aes(x=ps, fill=cellt)) +
      geom_density(alpha=.5) + theme_bw() +
      ggtitle("D")
pD

pE <- ggplot(GO_toPlot_ALL,aes(x = Module , y = Term)) +  
    geom_point(aes(size= -log(as.numeric(P)), color= Interval)) + scale_size(range = c(4, 8)) +
    scale_color_manual(values=c("orange1"))+ theme(axis.text.y = element_text( color = "black",size = 10)) + theme(axis.text.x = element_text( color = "black",size = 10, angle = 90,hjust=1)) + guides(colour = guide_legend(override.aes = list(size=8))) +
      ggtitle("E")
pE
